using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using HalconDotNet;
namespace Rbt6100AutoLine
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        private void action()
        {
            // Local iconic variables 

            HObject ho_Image = null;

            // Local control variables 

            HTuple hv_AcqCam = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_Image);
            //Image Acquisition 01: Code generated by Image Acquisition 01
            //  HOperatorSet.ClearWindow(hv_ExpDefaultWinHandle);
            HOperatorSet.OpenFramegrabber("GigEVision", 0, 0, 0, 0, 0, 0, "default", -1,
                "default", -1, "false", "default", "000748dcdbab_TheImagingSourceEuropeGmbH_DFK33G4",
                0, -1, out hv_AcqCam);
            HOperatorSet.GrabImageStart(hv_AcqCam, -1);
            while ((int)(1) != 0)
            {
                ho_Image.Dispose();
                HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqCam, -1);
                HOperatorSet.DispObj(ho_Image, hWindowControl1.HalconWindow);
                //     h
                //Image Acquisition 01: Do something
            }
            HOperatorSet.CloseFramegrabber(hv_AcqCam);
            ho_Image.Dispose();

        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {
            HObject ho_Image = null;

            // Local control variables 

            HTuple hv_AcqCam = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_Image);
            //Image Acquisition 01: Code generated by Image Acquisition 01
            //  HOperatorSet.ClearWindow(hv_ExpDefaultWinHandle);
            try
            {
                HOperatorSet.OpenFramegrabber("GigEVision", 0, 0, 0, 0, 0, 0, "default", -1,
  "default", -1, "false", "default", "000748dcdbab_TheImagingSourceEuropeGmbH_DFK33G4",
  0, -1, out hv_AcqCam);
            }
            catch (HOperatorException ex)
            {
                MessageBox.Show(ex.GetErrorMessage());
            }
            HOperatorSet.GrabImageStart(hv_AcqCam, -1);
            while (true)
            {
                ho_Image.Dispose();
                HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqCam, -1);
                HOperatorSet.DispObj(ho_Image, hWindowControl1.HalconWindow);
            }
            HOperatorSet.CloseFramegrabber(hv_AcqCam);
            ho_Image.Dispose();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            backgroundWorker1.RunWorkerAsync();
        }
    }
}
